try 语句测试代码块的错误。
catch 语句处理错误。
throw 语句创建自定义错误。
try
  {
  //在这里运行代码
  }
catch(err)
  {
  //在这里处理错误
  }